name: Validate tar based distributions

on:
  pull_request_target:
    paths: ['distributions/**']

jobs:
  check:
    name: Validate tar based distributions changes
    runs-on: ubuntu-latest
    permissions:
        pull-requests: write
    steps:
        - name: Checkout official repo
          uses: actions/checkout@v4
          with:
            repository: 'microsoft/WSL'
            ref: master
            fetch-depth: 0

        - name: Checkout repo
          uses: actions/checkout@v4
          with:
            ref: refs/pull/${{ github.event.pull_request.number }}/merge
            fetch-depth: 0
            path: source_repo

        - name: Install pip packages
          run: pip install -r distributions/requirements.txt
          shell: bash

        - name: Run validation
          run: | 
            python distributions/validate-modern.py \
            --repo-path . \
            --compare-with-branch 'origin/${{ github.base_ref }}' \
            --manifest source_repo/distributions/DistributionInfo.json \
            --github-token '${{ secrets.GITHUB_TOKEN }}' \
            --github-pr '${{ github.event.pull_request.number }}' \
            --github-commit '${{ github.sha }}'
          shell: bash
